opcodes = {'createaccount': '1',
            'login': '2',
            'exit': '3',
            'startchat': '4',
            'INPUT': 'a',
            'SHOW': 'b',
            'CONNECT': 'c',
            'DELETE': 'd',
            'EXIT_CHAT': 'e',
            'TEXT': 't'}