# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\nhelloworld\"\x07\n\x05\x45mpty\"\"\n\x0fRequestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0b\x43hatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t2\xc0\x03\n\x0b\x43hatService\x12\x46\n\x0bGetMessages\x12\x1a.helloworld.MessageRequest\x1a\x17.helloworld.ChatMessage\"\x00\x30\x01\x12\x41\n\x0bSendMessage\x12\x17.helloworld.ChatMessage\x1a\x17.helloworld.ChatMessage\"\x00\x12\x39\n\x08GetUsers\x12\x17.helloworld.UserRequest\x1a\x10.helloworld.User\"\x00\x30\x01\x12\x38\n\x05Login\x12\x10.helloworld.User\x1a\x1b.helloworld.RequestResponse\"\x00\x12\x39\n\x06Logout\x12\x10.helloworld.User\x1a\x1b.helloworld.RequestResponse\"\x00\x12;\n\x08Register\x12\x10.helloworld.User\x1a\x1b.helloworld.RequestResponse\"\x00\x12\x39\n\x06\x44\x65lete\x12\x10.helloworld.User\x1a\x1b.helloworld.RequestResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=26
  _EMPTY._serialized_end=33
  _REQUESTRESPONSE._serialized_start=35
  _REQUESTRESPONSE._serialized_end=69
  _CHATMESSAGE._serialized_start=71
  _CHATMESSAGE._serialized_end=101
  _MESSAGEREQUEST._serialized_start=103
  _MESSAGEREQUEST._serialized_end=136
  _USERREQUEST._serialized_start=138
  _USERREQUEST._serialized_end=168
  _USER._serialized_start=170
  _USER._serialized_end=190
  _CHATSERVICE._serialized_start=193
  _CHATSERVICE._serialized_end=641
# @@protoc_insertion_point(module_scope)
